### ISSUE TITLE
Idea: Idle Game Capability

### ISSUE THREAD

**Issue by GlennHS** [peep24/kitten_generator#2]
Hi @peep24,
I'm aware this was probably a fun little project and as such this issue can be safely ignored but thought I'd leave a comment (well, issue. Github doesn't appear to have comment functionality as of yet) just to say that this is a great little page and also have you considered as a side project maybe turning it into some little idle game? I can imagine by using either `localStorage` calls when the page is closed or by some other method you could actually have persistent kitty storage. On top of this you could possibly even game-ify it into some sort of idle game. Maybe a good portfolio piece or just a fun little side project!

Great work as always, I'm paws-itive you're a great developer!

p.s. Is having a kitty's health go above 100% intended functionality? If not I'm happy to raise a new issue for this, just let me know

**Comment by peep24** [comment]
It is so annoying GitHub doesn't have comment functionality, or reactions to a lot of the activity. 

Thanks man. TBH I just wanted to Dan to try and pet his kitty and watch it die. Nothing other than pure maniacal pleasure. I could build it out but I haven't got time at the moment! Glad to see your on the Laravel train! Welcome to the party!
